  export const videos = [
    {
      image: 'assets/images/img1.png',
      title: 'Friends',
      episode: 23,
      percentDone: '45%',
      screens: '16',
      indexRecord: 1000000,
      sceneViews: 1000000,
      adViews: 1000000,
      adLikes: 1000000,
      adClicks: 1000000,
      seasons: [
        {
          title: 'Season 1',
          episode: 23,
          percentDone: '45%',
          screens: '16',
          indexRecord: 1000000,
          sceneViews: 1000000,
          adViews: 1000000,
          adLikes: 1000000,
          adClicks: 1000000,
          episodes: [
            {
              title: 'Episode 01',
              percentDone: '45%',
              screens: '16',
              indexRecord: 1000000,
              sceneViews: 1000000,
              adViews: 1000000,
              adLikes: 1000000,
              adClicks: 1000000,
              scenes: [{
                title: 'Scene 01',
                image: 'assets/images/scenes.jpg',
                count: '88',
                screensCount: '16',
                tag: 2,
                sceneViews: 3,
                adViews: 23,
                adLikes: 56,
                adClicks: 4,
                screens: [{
                  title: 'Friends',
                  image: 'assets/images/img1.png',
                  season: 'S02',
                  episode: 'E09',
                  scene: 'SC288',
                  sceneView: "assets/images/scenes.jpg",
                  tagId: 'FRIENDSS02E13SC288T1000',
                  topVZOTScore: 56,
                  tagger: 'Amanda Appleseed',
                  proxy: 'assets/images/img1.png',
                  superProxy: 'assets/images/img1.png',
                  actor: 'jennifer Aniston',
                  actorImage: 'assets/images/img1.png',
                  superProxySource: 'Nordstom',
                  gender: 'Female',
                  color: 'Brown',
                  pattern: 'Chekered',
                  subCategories: 'Leather Jacket, Motorcycle',
                  attributes: 'Leather Jacket, Motorcycle',
                  coordinates: 'X: 58%, Y: 58%,',
                  admatch1: 'assets/images/img1.png',
                  advertiser1: 'Nordstrom',
                  vZOTScore1: 99,
                  admatch2: 'assets/images/img1.png',
                  advertiser2: 'Nordstrom',
                  vZOTScore2: 99,
                  admatch3: 'assets/images/img1.png',
                  advertiser3: 'Nordstrom',
                  vZOTScore3: 99,
                  tagDate: '03/04/2023',
                  timecodeStart: '00:00:00',
                  timecodeEnd: '00:00:00',
                  description: 'This shows two lines of copy a...',
                  brand: 'Lucky',
                  price: '$39.99',
                  scorethumbImageID: '0000000',
                  proxy1ImageID: '0000000',
                  superProxy1ImageId: '0000000',
                  superProxy2ImageId: '0000000',
                  superProxy3ImageId: '0000000',
                  posterImageId: '0000000',

                }]
              },]
            },
            {
              title: 'Episode 02',
              percentDone: '45%',
              screens: '16',
              indexRecord: 1000000,
              sceneViews: 1000000,
              adViews: 1000000,
              adLikes: 1000000,
              adClicks: 1000000,
            },
            {
              title: 'Episode 03',
              percentDone: '45%',
              screens: '16',
              indexRecord: 1000000,
              sceneViews: 1000000,
              adViews: 1000000,
              adLikes: 1000000,
              adClicks: 1000000,
            },
          ]
        }
      ]
    },

  ]