import { environment } from "../../../environments/environment";

export const requests = {

    login: environment.baseUrlAdmin + '/api/user/login',
    getAllStats: environment.baseUrlAdmin + '/api/stat/getAllStats',
    streamerTopStats: environment.baseUrlAdmin + '/api/streamer/getTopStats',
    streamerPopularShows: environment.baseUrlAdmin + '/api/streamer/getPopularShows',
    getMostActiveUsers: environment.baseUrlAdmin + '/api/user/viewer/mostActive',
    getTrendingActors: environment.baseUrlAdmin + '/api/actor/getTrendingActors',
    getTrendingShows: environment.baseUrlAdmin + '/api/show/getTrendingShows',
    getTopTaggers: environment.baseUrlAdmin + '/api/user/tagger/getTopTaggers',
    getSeriesName: environment.baseUrlAdmin + '/api/show/getSeriesName',
    getAllSeasonofSeries: environment.baseUrlAdmin + '/api/show/getSeasonsOfShow',
    getAllEpisodesofSeason: environment.baseUrlAdmin + '/api/show/getAllEpisodeBySeasonNo',
    getTagger: environment.baseUrlAdmin + '/api/user/tagger/getTaggers',
    getAvgVzot: environment.baseUrlAdmin + '/api/stat/avgVzot',
    getStreamerRevenue: environment.baseUrlAdmin + '/api/streamer/getStreamerRevenue',
    getAllShowListing: environment.baseUrlAdmin + '/api/show/getAllShowListing',
    getCloudStatus: environment.baseUrlAdmin + '/api/cloud/status',
    toggleEnvironment: environment.baseUrlAdmin + '/api/cloud/toggleInstancesState',
    // getCloudCosts:environment.baseUrlAdmin+'api/cloud/cost',
    updateUser: environment.baseUrlAdmin + '/api/user/profile/update',
    episodePreview: environment.baseUrlAdmin + '/api/show/getEpisodePreview',
    addNewSeries: environment.baseUrlAdmin + '/api/show/addNewSeries',
    getImageUrl: environment.baseUrlAdmin + '/api/cloud/gcp/generateSignedUrl',
    addNewVideo: environment.baseUrlAdmin + '/api/show/addNewVideo',
    getCloudCosts: environment.baseUrlAdmin + '/api/cloud/cost',
    getAllCreator: environment.baseUrlAdmin + '/api/creator/getAllCreator',
    getCumulativeCloudCosts: environment.baseUrlAdmin + '/api/cloud/cost/cumulative',
    updateTaggerStatus: environment.baseUrlAdmin + '/api/user/tagger/updateTaggerStatus',
    getTaggerStats: environment.baseUrlAdmin + '/api/user/tagger/getTaggerStats',
    getTaggerTagsShow: environment.baseUrlAdmin + '/api/show/getTaggerTagsShow',
    getTaggerSceneListing: environment.baseUrlAdmin + '/api/scene/getTaggerScenesListing',
    getProductsOfCoordinate: environment.baseUrlAdmin + '/api/scene/getProductsOfCoordinate',
    updateSceneById: environment.baseUrlAdmin + '/api/scene/updateSceneById',
    updateSceneByShowId: environment.baseUrlAdmin + '/api/scene/updateSceneByShowId',
    getActors: environment.baseUrlAdmin + '/api/actor/getActors',
    recognizeActors: environment.baseUrlAdmin + '/api/actor/recognizeActors',
    addActor: environment.baseUrlAdmin + '/api/actor/addActor',
    deleteActor: environment.baseUrlAdmin + '/api/actor/deleteActor',
    getShowActors: environment.baseUrlAdmin + '/api/actor/getShowActors',
    getUserProfile: environment.baseUrlAdmin + '/api/user/profile/get',
    getTrending: environment.baseUrlAdmin + '/api/product/getTrending',
    getTopProductsByShow: environment.baseUrlAdmin + '/api/getTopProductsByShow',
    getTopProductsByBrand: environment.baseUrlAdmin + '/api/getTopProductsByBrand',
    getTopProductsByActor: environment.baseUrlAdmin + '/api/getTopProductsByActor',
    getProductsOfSceneByRetailer: environment.baseUrlAdmin + '/api/scene/getProductsOfSceneByRetailer',
    getProductByProxy: environment.baseUrlAdmin + '/api/product/getProductByProxy',
    getSeasons: environment.baseUrlAdmin + '/api/show/getSeasonsOfShow',
    getEpisodes: environment.baseUrlAdmin + '/api/show/getAllEpisodeBySeasonNo',
    addTag: environment.baseUrlAdmin + '/api/tag/addTag',
    updateTag: environment.baseUrlAdmin + '/api/tag/updateTag',
    tagProductInScene: environment.baseUrlAdmin + '/api/scene/tagProductInScene',
    addNewCreator: environment.baseUrlAdmin + '/api/creator/addNewCreator',
    getUserListing: environment.baseUrlAdmin + '/api/user/getUserListing',
    assignShowToTagger: environment.baseUrlAdmin + '/api/show/assignShowToTagger',
    getSceneByIdAndTopAds: environment.baseUrlAdmin + '/api/scene/getSceneByIdAndTopAds',
    getAllAdvertisersForAdmin: environment.baseUrlAdmin + '/api/advertiser/getAllAdvertiserForAdmin',
    getStreamersWithAdvertisers: environment.baseUrlStreamer + '/api/advertiser/getStreamersAndTheirAdvertisers',
    getStreamersWithShows: environment.baseUrlStreamer + '/api/show/getAllStreamersWithShows',
    getAllAdvertiser: environment.baseUrlAdmin + '/api/advertiser/getAllAdvertisersByCategory',//'/api/advertiser/getAllAdvertisers',
    getAllAdvertiserByCategory: environment.baseUrlAdmin + '/api/advertiser/getAllAdvertisersByCategory',
    getTopSuperProxyProduct: environment.baseUrlAdmin + '/api/getTopSuperProxyProduct',
    getTrendingAds: environment.baseUrlAdmin + '/api/getTrendingAdsProduct',
    getAdvertiserById: environment.baseUrlAdmin + '/api/advertiser/getAdvertiserById',
    getUserById: environment.baseUrlAdmin + '/api/user/getUserById',
    updateUserByAdmin: environment.baseUrlAdmin + '/api/user/updateUserByAdmin',
    createUser: environment.baseUrlAdmin + '/api/createUser',
    getCountries: environment.baseUrlAdmin + '/api/countries/getCountries',
    getAllShowForAdvertiser: environment.baseUrlAdmin + '/api/advertiser/getAllShowForAdvertiser',
    getSceneById: environment.baseUrlAdmin + '/api/scene/getSceneById',
    getAlgoScores: environment.baseUrlAdmin + '/api/product/getAlgoScores',
    updateAlgoScores: environment.baseUrlAdmin + '/api/product/updateAlgoScores',
    getSeriesById:environment.baseUrlAdmin+'/api/show/getSeriesById',
    updateSeriesById:environment.baseUrlAdmin+'/api/show/updateSeriesById',
    addToWishlist:environment.baseUrlAdmin+'/api/user/wishlist/add',
    removeFromWishList:environment.baseUrlAdmin+'/api/user/wishlist/remove',
    getAllScenes:environment.baseUrlAdmin+'/api/scene/getAllScenes',
    deleteSceneNotes:environment.baseUrlAdmin+'/api/scene/deleteSceneNotes',
    deleteUser:environment.baseUrlAdmin+'/api/user/deleteUser',
    deleteTagger:environment.baseUrlAdmin+'/api/user/deleteTagger',
    deleteEpisode:environment.baseUrlAdmin+'/api/show/deleteEpisode',
    deleteShow:environment.baseUrlAdmin+'/api/show/deleteShow',
    getEmbedding:environment.baseUrlAdmin+'/api/cloud/gcp/getEmbedding',
    getProductsByEmbedding: environment.baseUrlAdmin + '/api/product/getProductsByEmbedding',
    getProductsByImageEmbedding: environment.baseUrlAdmin + '/api/product/getProductsByImageEmbedding',
    getStreamerApiKeys: environment.baseUrlAdmin + '/api/misc/getApiKeys',
    deleteStreamerApiKey: environment.baseUrlAdmin + '/api/misc/deleteApiKey',
    generateStreamerApiKey: environment.baseUrlAdmin + '/api/misc/generateApiKey',
    getProductsByTextEmbedding: environment.baseUrlAdmin + '/api/product/getProductsByTextEmbedding',
    searchProductsInScenes: environment.baseUrlAdmin + '/api/product/searchProductsInScenes',
    getCategories: environment.baseUrlAdmin + '/api/product/getCategories',
    updateVideoPlays: environment.baseUrlAdmin + '/api/user/updateVideoPlays',
    updateEmailImpressions: environment.baseUrlAdmin + '/api/user/updateEmailImpressions',
    updateRetargetImpressions: environment.baseUrlAdmin + '/api/user/updateRetargetImpressions',
    updateDiscoveryImpressions: environment.baseUrlAdmin + '/api/user/updateDiscoveryImpressions',
    swapProxyCoordinates: environment.baseUrlAdmin + '/api/scene/swapProxyCoordinates',
    sendFeedback: environment.baseUrlAdmin + '/api/user/sendFeedback',
    sendMediaBuyEmail: environment.baseUrlAdmin + '/api/sendMediaBuy',
    getScenesByRetailerAndTopAds: environment.baseUrlAdmin + '/api/scene/getScenesByRetailerAndTopAds',
    getAdvertisersMatchesByShowId :environment.baseUrlAdmin + '/api/advertiser/getAdvertisersMatchesByShowId',
    sendReactivationRequest: environment.baseUrlAdmin + '/api/userReactivation',

    //pythonApi
    openAiFilters: environment.pythonBaseUrl + '/open_ai_filters',
    //dont use these
    rejectGovernment: environment.baseUrlAdmin + '/admin/accounts/government/reject-government-company/',
    rejectbusiness: environment.baseUrlAdmin + '/admin/accounts/business/reject-business-company/',
    getProgresSeries: environment.baseUrlAdmin + '/api/show/getProgressBySeries',
    addNewAttachment: environment.baseUrlAdmin + 'attachments',
    videoShowListing: environment.baseUrlAdmin + '/api/show/getAllShowListing',
    coordinateListingForAdmin: environment.baseUrlAdmin + '/api/getCoordinateListingForAdmin',
    getShowScenes: environment.baseUrlAdmin + '/api/show/getShowScenes',
    getSceneDetails: environment.baseUrlAdmin + '/api/scene/getScenes',
    getSceneCooerdinates: environment.baseUrlAdmin + '/api/scene/getCoordinateByScene',
    getProxyCoordinateById: environment.baseUrlAdmin + '/api/scene/getProxyCoordinateById',
    updateTagProductInScene: environment.baseUrlAdmin + '/api/scene/updateTagProductInScene',
    getCoordinatesAndProducts: environment.baseUrlAdmin + '/api/show/getCoordinatesAndProducts',
    getUpdateAdvertiser: environment.baseUrlAdmin + '/api/advertiser/updateAdvertiser',
    updateShowStatus: environment.baseUrlAdmin + '/api/show/updateShowStatus',
    // getShowScenes: environment.baseUrlAdmin + '/api/show/getShowScenes',
    downloadDatabase: environment.baseUrlAdmin + '/api/cloud/downloadDatabase',
    getCoordinateListingForAdInventory: environment.baseUrlAdmin + '/api/getCoordinateListingForAdInventory',
    getProductsById: environment.baseUrlAdmin + '/api/product/getProductById',
    deleteAdInEpPreview: environment.baseUrlAdmin + '/api/product/eliminateProductFromAdQueue',
    deleteAdGCP: environment.baseUrlAdmin + '/api/product/eliminateProductsFromGCPSearch',
    getSceneNotes: environment.baseUrlAdmin + '/api/scene/getNotesBySceneId',
    updateSceneNotes: environment.baseUrlAdmin + '/api/scene/updateNotesStatus',
    addSceneNotes: environment.baseUrlAdmin + '/api/scene/addSceneNotes',
    requestForProxy: environment.baseUrlAdmin + '/api/product/getProductByProxy',
    updateEpPreview: environment.baseUrlAdmin + '/api/scene/tagProductsFromEpisodePreview',
    getUserName: environment.baseUrlAdmin + '/api/user/getUsername',
    tagRecentProxies: environment.baseUrlAdmin + '/api/scene/tagProductFromExistingPR'
}

export const patterns = {
    url: '(https?://).*?'
}
